from decouple import config

KAFKA_BOOTSTRAP_SERVERS = config("KAFKA_BOOTSTRAP_SERVERS")
KAFKA_TOPIC = config("KAFKA_TOPIC")
REDIS_HOST = config("REDIS_HOST")
REDIS_PORT = config("REDIS_PORT", cast=int)
REDIS_DB = config("REDIS_DB")
HDFS_BATCH_TOPIC=config("HDFS_BATCH_TOPIC")
LOG_CENTRAL_KAFKA_TOPIC=config("LOG_CENTRAL_KAFKA_TOPIC")

BOOTSTRAP_SERVERS_137 = config("BOOTSTRAP_SERVERS_137")
KAFKA_137_KERBEROS_SERVICE_NAME = config("KAFKA_137_KERBEROS_SERVICE_NAME")
KEYTAB_137 = config("KEYTAB_137")
PRINCIPAL_137 = config("PRINCIPAL_137")

LOG_CENTRAL_BOOTSTRAP_SERVERS = config("LOG_CENTRAL_BOOTSTRAP_SERVERS")
LOG_CENTRAL_KAFKA_GROUP_ID = config("LOG_CENTRAL_KAFKA_GROUP_ID")
